engines:
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
      Generic WhiteSpace ScopeIndent IncorrectExact:
        enabled: false
      PSR2 Files ClosingTag NotAllowed:
        enabled: false
ratings:
  paths:
  - "**.php"

